### PR TITLE
#159361719 User Can Cancel Order

### PR DESCRIPTION
**Pull request by Onnassiz**
#### What does this PR do?
This PR creates an order page where customers can cancel orders and manage order.
#### Description of Task to be completed?
- Create order component to display all custom orders
  - Setup order component route
  - Add route link to nav bar
  - Add order table
  - Add condition for order cancel
  - Add pagination to tables
  - Add cancel order feature
  - Add order summary modal
  - Remove order listing from profile page
#### How should this be manually tested?
This PR can be tested using the review app link created below
#### What are the relevant pivotal tracker stories?
#159361719
#### Any background context you want to add?
There may be a need to grant /order page access to the customer group as a shop owner in order for customers to be able to access the other page.
#### Screenshots
screen shot 2018-08-20 at 5 53 38 pm
screen shot 2018-08-20 at 5 53 58 pm
screen shot 2018-08-20 at 5 54 13 pm

### CODE REVIEW

**Comment by Nkemjiks** [comment]
Hi @Onnassiz, the screenshots looks very good. You clearly followed the design already in place in RC. I was able to place an order but I can't view them. Below is the page that was displayed.
screen shot 2018-08-23 at 11 18 08 am

Please look into it. I would also suggest that you add the card generator site to the PR so that everyone can easily test the review app.

**Comment by Onnassiz** [comment]
Hi @Nkemjiks. Thanks for raising this issue. I have resolved it. It turns out the PR raised by @Hasstrup is deleting the /orders role in the DB. I think we need to modify our review app setting so that each PR will have their own unique database to avoid data inconsistencies.

**Comment by Onnassiz** [comment]
Kindly check the review app again.

**Comment by Nkemjiks** [comment]
It is working as expected @Onnassiz. Weldone

**Review by Nkemjiks — APPROVED** [review]
Meets the acceptance criteria and implements what was specified in the dev note for the story

**Review by kenware — APPROVED** [review]
Nice work @Onnassiz, I hereby approve your PR

**Pull request merged**
