### PR TITLE
#159361720 Paystack Integration

### PR DESCRIPTION
**Pull request by Nkemjiks**
#### What does this PR do?
Setup Paystack as a payment option when checking out

#### Description of Task to be completed?
A customer should be able to checkout the cart and make payment with Paystack if its integrated

#### How should this be manually tested?
Go to the review app, activate Paystack as your payment option. Enter your secret key and public key. Add an item to cart, checkout the item and enter your paystack details.

#### What are the relevant pivotal tracker stories?
#159361720

#### Any background context you want to add?
N/A

#### Screenshots
screen shot 2018-08-17 at 12 52 13 pm
screen shot 2018-08-17 at 12 56 25 pm
screen shot 2018-08-17 at 12 57 01 pm
screen shot 2018-08-17 at 12 56 13 pm
screen shot 2018-08-17 at 12 55 58 pm
screen shot 2018-08-17 at 12 55 27 pm

### CODE REVIEW

**Comment by Onnassiz** [comment]
Hi @Nkemjiks and @Dikaeinstein. I am quite impressed by how you have implemented this task that seemed impossible at first. I noticed the section where a super admin can enable paystack integration on a shop to allow customers to pay the pay stack this medium.

I would like to know if a shop owner can enable more than one payment method. If so, can you please explain to me the expected behavior of the software in a case where a customer has to choose one of many available payment options?

**Comment by Nkemjiks** [comment]
Hi @Onnassiz, Thanks for the question. Here is a screenshot from RC webpage that answers your question
screen shot 2018-08-23 at 1 32 48 pm
Here is a link to the page: https://docs.reactioncommerce.com/docs/payment
You can definitely add more than one payment option. When a customer wants to checkout, they will given the option to select which payment option they want to use and they will redirected as expected.

**Review by Onnassiz — APPROVED** [review]
Good job guys. Keep it up.

**Comment by Onnassiz** [comment]
Thanks, @Nkemjiks for your response. It is quite helpful.

**Comment by Hasstrup** [comment]
Great Job @Nkemjiks and @Dikaeinstein, I am particularly impressed with the attention you paid to detail (as seen in the receipt that is mailed to the user). Good Job!

**Review by Hasstrup — APPROVED** [review]
Looks like you followed conventions and stuck to best practices. Hopefully, we can get some tests the next time we get a pull request.

**Pull request merged**
